(eval-when-compile
  (require 'use-package))

(use-package use-package
  :ensure t)
(use-package evil
    :ensure t)
(use-package airline-themes
  :ensure t)
(use-package ace-window
    :ensure t)
(use-package anzu
    :ensure t)
;; (use-package auctex
;;   :ensure t
;;   :defer t
;;   :pin gnu)
(use-package avy
    :ensure t)
(use-package bash-completion
    :ensure t)
(use-package company
    :ensure t)
(use-package elpy
    :ensure t)
(use-package evil-anzu
    :ensure t)
(use-package evil-escape
    :ensure t)
(use-package evil-nerd-commenter
    :ensure t)
(use-package evil-snipe
   :ensure t)
(use-package evil-surround
    :ensure t)
(use-package expand-region
    :ensure t)
(use-package fill-column-indicator
    :ensure t)
(use-package flycheck
    :ensure t)
(use-package flyspell
    :ensure t)
(use-package general
    :ensure t)
(use-package golden-ratio-scroll-screen
    :ensure t)
(use-package helm
    :ensure t)
(use-package highlight-indentation
    :ensure t)
(use-package magit
    :ensure t)
(use-package evil-magit
  :ensure t)
(use-package neotree
    :ensure t)
(use-package org
    :ensure t)
(use-package org-ref
    :ensure t)
(use-package powerline
    :ensure t)
(use-package rainbow-delimiters
    :ensure t)
(use-package reftex
    :ensure t)
(use-package rich-minority
    :ensure t)
(use-package smartparens
    :ensure t)
(use-package sudo-edit
    :ensure t)
(use-package window-numbering
    :ensure t)
(use-package yasnippet
    :ensure t)
(use-package pdf-tools
  :ensure t)
(use-package ggtags
  :ensure t)
(use-package pcomplete-extension
  :ensure t)
(use-package ranger
  :ensure t)
(use-package company-quickhelp
  :ensure t)
(use-package fish-completion
  :ensure t)
(use-package pyim
  :ensure t)
(use-package posframe
  :ensure t)
(use-package langtool
  :ensure t)
(use-package eshell-z
  :ensure t)
(use-package paradox
  :ensure t)
(use-package atomic-chrome
  :ensure t)
(use-package artbollocks-mode
  :ensure t)
(use-package interleave
  :ensure t)
(use-package evil-matchit
  :ensure t)
(use-package evil-exchange
  :ensure t)
(use-package company-flx
  :ensure t)
(use-package flyspell-correct
  :ensure t)
(use-package flyspell-correct-popup
  :ensure t)
(use-package winum
  :ensure t)
(use-package define-word
  :ensure t)
(use-package powerthesaurus
  :ensure t)
(provide 'init-use-package)
