(add-hook 'python-mode-hook 'flycheck-mode)
'(flycheck-error ((t (:slant italic))))
'(flycheck-warning ((t (:slant italic))))
'(flymake-errline ((t nil)))
'(secondary-selection ((t (:background "gray95"))))
(provide 'init-flycheck)
