(global-set-key (kbd "M-[") 'ace-window)
(setq aw-background nil)
;; (setq aw-keys '(?a ?s ?d ?f ?g ?h ?j ?k ?l))
;; (setq aw-dispatch-always t)
;; (ace-window-display-mode 1)
(provide 'init-ace-window)
